import type { Metadata } from "next";
import "./globals.css";
import Nav from "@/components/nav/nav";
import Footer from "@/components/footer/foter";
import { poppins } from "@/app/font";
import { AuthProvider } from "./context/auth";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AuthProvider>
          <Nav />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
